config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :images
  resources :galleries
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'galleries#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
# frozen_string_literal: true

class Gallery < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :images, dependent: :destroy

  mount_uploader :cover_image, ImageUploader
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :gallery

  mount_uploader :url, ImageUploader
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, :password, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :galleries, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/galleries_controller.rb
# frozen_string_literal: true

class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show; end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit; end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(name: params[:name], user_id: current_user.id)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gallery_params
    params.permit(:name, :cover_image)
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  before_action :set_image, only: %i[show edit update destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show; end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit; end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(url: params[:url], gallery_id: params[:gallery_id])
    respond_to do |format|
      if @image.save
        format.html { redirect_to gallery_path(@image.gallery_id), notice: 'Image was successfully uploaded.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully uploaded.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to gallery_path(@image.gallery_id), notice: 'Image was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def image_params
    params.require(:image).permit(:url)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/galleries_helper.rb
# frozen_string_literal: true

module GalleriesHelper
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/galleries/_form.html.erb
<%= form_with(model: gallery, local: true) do |form| %>
  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with url: galleries_path do |form| %>
    <div class="input-group mb-3">
      <%= form.text_field :name, placeholder: "Enter new album name", class: "form-control" %>
      <br>
      <div class="input-group-append">
        <br>
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

<% end %>

app/views/galleries/edit.html.erb
<div class="container">
	<h1 class="galleries-title">Edit Album</h1>
	<%= render 'form', gallery: @gallery %>
	<%= link_to 'Show', @gallery %> |
	<%= link_to 'Back', galleries_path %>
</div>

app/views/galleries/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 class="galleries-title">Galleries</h1>

  <% if current_user %>
    <%= link_to 'Create New Gallery', new_gallery_path %>
  <% end %>
      
  <% @galleries.each do |gallery| %>
    <div class="gallery-container">
      <div class="row mx-lg-n5">
        <div class="col-12 col-md-5">
          <% if gallery.images.first %>
            <a href="<%= gallery_path(gallery.id) %>"><%= image_tag(gallery.images.first.url.cover.url) %></a>
          <% end %>
        </div>
        <div class="col-6 col-md-7 album-info">
          <h2 class="album-title"><%= gallery.name %></h2>
          <%= gallery.created_at.strftime('%d-%m-%Y %H:%M:%S') %>
          <br>
          <% if current_user %>
            <% if current_user.id == gallery.user_id %>
              <%= link_to 'Edit', edit_gallery_path(gallery) %>   |
              <%= link_to 'Delete', gallery, method: :delete, data: { confirm: 'Are you sure?' } %>
              <br>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  
  <% end %>

  <br>
 
</div>

app/views/galleries/new.html.erb
<div class="container">
	<h1 class="galleries-title">Create New Gallery</h1>

	<%= render 'form', gallery: @gallery %>
	<%= link_to 'Back', galleries_path %>
</div>

app/views/galleries/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="album-container">
      <div class="row mx-lg-n5">
        <div class="col-12 col-md-5">
          <% if @gallery.images.first %>
            <a href="<%= gallery_path(@gallery.id) %>"><%= image_tag(@gallery.images.first.url.cover.url) %></a>
          <% end %>
        </div>
        <div class="col-6 col-md-7 album-info">
          <h2 class="album-title"><%= @gallery.name %></h2>
          <%= @gallery.created_at.strftime('%d-%m-%Y %H:%M:%S') %>
          <br>
          <%= link_to 'Back', galleries_path %> |
          <% if current_user %>
            <% if current_user.id == @gallery.user_id %>
              <%= link_to 'Edit', edit_gallery_path(@gallery) %>  |
              <%= link_to 'Delete', @gallery, method: :delete, data: { confirm: 'Are you sure?' } %>
              <br>
              <br>
              <%= form_with(url: images_path) do |form| %>
                <div class="field">
                  <br>
                  <%= form.label :upload_image_to_album %>
                  <%= form.file_field :url, required: true %>
                </div>
                <%= form.hidden_field :gallery_id, value: @gallery.id %>
                <br>
                <div class="actions">
                  <%= form.submit "Upload image", class: "btn btn-primary" %>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>

    <h4 class="images-title">Images in gallery:</h4>            
    <% @gallery.images.each do |image| %>
      <tr>
        <a href="<%= image_path(image.id) %>"><td><%= image_tag(image.url.thumbnail.url) %></td></a>
      <tr>
    <% end %>

  </div>
</div>

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.file_field :url, required: true %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit class:"btn btn-primary btn-md"  %>
  </div>
<% end %>

app/views/images/edit.html.erb
<div class="container">
	<h1 class="galleries-title">Replace Image</h1>

	<img class="img">
		<%= image_tag(@image.url.cover.url) %>
	</img>
	 
	<%= render 'form', image: @image %>
	<%= link_to 'Show', @image %> |
	<%= link_to 'Back', gallery_path(@image.gallery_id) %>
</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <p>
    <img class="img">
      <%= image_tag(@image.url.image.url) %>
    </img>
    <br>
    <h4>Image uploaded at:</h4>
    <%= @image.updated_at.strftime('%d-%m-%Y %H:%M:%S') %>
  </p>

  <%= link_to 'Back', gallery_path(@image.gallery_id) %> 
  <% if current_user %>
    <% if current_user.id == Gallery.find(@image.gallery_id).user_id %>
      |<%= link_to 'Edit', edit_image_path(@image) %> |
      <%= link_to 'Delete', image_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => "users/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/users/_navbar.html.erb
<div class="fluid-container">
  <nav class="navbar-nav navbar-inverse col-xs-12">
    <%= image_tag("logo.png", class: "logo")%>
    <span class="navbar-nav col-xs-10 nav-title h1">My Gallery</span>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
         <li><%= link_to "Login", new_user_session_path %></li>
         <li><%= link_to "Register", new_user_registration_path %></li>
      <% end %>
    </ul>
  </nav>
</div>
  